fss_sim_time_broker:
  ros__parameters:
    max_speed_ratio: 1.0
    max_real_time_factor: 1.0
    helics_core_type: zmq
    helics_broker_address: 127.0.0.1
    helics_broker_port: 23404
    helics_broker_federates: 0
    helics_time_delta_ns: 1000000
    start_helics_broker: true
