name: ROS 2 Humble Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  humble_build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
    steps:
      - name: Build ROS 2 workspace
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: >-
            fss_bringup
            fss_px4_sim
            fss_sensing
            fss_time
            fss_time_interfaces
          target-ros2-distro: humble
          skip-tests: "true"
